#pragma once
 

#define  RTSP_STATUS_OK 200
#define  RTSP_STATUS_METHOD 405
#define  RTSP_STATUS_BANDWIDTH 453
#define  RTSP_STATUS_SESSION 454
#define  RTSP_STATUS_STATE 455
#define  RTSP_STATUS_AGGREGATE 459
#define  RTSP_STATUS_ONLY_AGGREGATE 460
#define  RTSP_STATUS_TRANSPORT 461
#define  RTSP_STATUS_INTERNAL 500
#define  RTSP_STATUS_SERVICE 503
#define  RTSP_STATUS_VERSION 505
